### PR TITLE
Refactor

### PR DESCRIPTION
**Pull request by ggilder**
@faun 

Next step: rename repo

### CODE REVIEW

**Comment by ggilder** [comment]
Looks like Travis ran the linter. :+1:

**Comment by ggilder** [comment]
Made the Config struct a little more "OO". Could refactor manifest too, WDYT? I think the primary thing that could change would be functions like `CompareManifests(oldManifest, newManifest Manifest)` could change to something like `(m *Manifest) CompareToNew(newManifest *Manifest)`, which could be kind of nice.

**Comment by faun** [comment]
:+1:

**Comment by ggilder** [comment]
Renaming the repo now.

**Pull request merged**
